version: '2'

services:
  web:
    # El punto hace referencia al dockerfile en la app
    build: .
    # command: "npm run watch"
    depends_on:
      - db
    ports:
      - "3001:3000"
    environment:
      - MONGODB_CONNECT_URI=mongodb://db:27017/twheaterapp
    volumes:
      - .:/opt/app
      - /opt/app/node_modules
  db:
    image: mongo
    expose:
      - "27017"
    volumes:
      - mongodata:/data/db
volumes:
  mongodata:
    